/*
 * The settings screen in a browser: admin.js run against the page the plugin
 * really prints (preview/public/admin-settings.html, generated by
 * tools/admin-demo.js). Sections switch without a reload, the save bar knows
 * what is unsaved, and the preview posts the form without the options nonce.
 *
 *   node tests/admin-js.js
 */
'use strict';

const path = require('path');
const { JSDOM } = require('jsdom');
const fs = require('fs');
const html = fs.readFileSync(path.join(__dirname, '..', 'preview', 'public', 'admin-settings.html'), 'utf8').replace(/<script src="[^"]*admin\.js"><\/script>/, '');
const dom = new JSDOM(html, { url: 'http://x.test/admin/settings?tab=security', runScripts: 'dangerously', pretendToBeVisual: true });
const w = dom.window, d = w.document;
const calls = [];
w.fetch = (u, o) => { calls.push([u, o && o.body && o.body.toString()]); return Promise.resolve({ ok: true, text: () => Promise.resolve('<p>pv</p>') }); };
w.scrollTo = () => {}; w.HTMLElement.prototype.scrollIntoView = () => {};
w.eval(fs.readFileSync(path.join(__dirname, '..', 'signa', 'assets', 'js', 'admin.js'), 'utf8'));
w.addEventListener('load', run);

function run() {
const vis = () => [...d.querySelectorAll('[data-signa-pane]')].filter(p => !p.hidden).map(p => p.dataset.signaPane);
const ok = (l, c) => { console.log((c ? 'PASS ' : 'FAIL ') + l); if (!c) process.exitCode = 1; };
ok('initial ?tab honoured: ' + vis(), vis().join() === 'security');
d.querySelector('[data-signa-section="channels"]').dispatchEvent(new w.MouseEvent('click', { bubbles: true, cancelable: true, button: 0 }));
ok('click switches: ' + vis(), vis().join() === 'channels');
ok('url updated ' + w.location.search, w.location.search === '?tab=channels');
ok('nav current', d.querySelector('.signa-screen.is-current').dataset.signaSection === 'channels' && d.querySelector('[aria-current="page"]').dataset.signaSection === 'channels');
const bar = d.querySelector('[data-signa-savebar]');
ok('clean at start', bar.dataset.state === 'clean');
const tpl = d.getElementById('signa-sms-template');
const before = tpl.value;
tpl.setSelectionRange(0, 0);
d.querySelector('[data-signa-token="{phone}"]').click();
ok('token inserted: ' + tpl.value, tpl.value === '{phone}' + before);
ok('dirty', bar.dataset.state === 'dirty');
d.querySelector('[data-signa-reset]').click();
ok('reset restores', tpl.value === before && bar.dataset.state === 'clean');
const radio = d.querySelectorAll('.signa-opts input')[1];
radio.checked = true; radio.dispatchEvent(new w.Event('change', { bubbles: true }));
ok('opt selected ring', radio.closest('.signa-opt').classList.contains('is-selected'));
const tg = d.querySelector('input.signa-tgl'); ok('switch aria-checked', tg.getAttribute('aria-checked') === String(tg.checked));
d.querySelector('[data-signa-goto]') && ok('goto link exists', true);
d.querySelector('[data-signa-section="formskin"]').dispatchEvent(new w.MouseEvent('click', { bubbles: true, cancelable: true, button: 0 }));
d.querySelector('[data-signa-preview-step="code"]').click();
setTimeout(() => {
  ok('preview posted with step=code and no _wpnonce: ' + (calls[0]||[''])[0], calls.length > 0 && /step=code/.test(calls[calls.length-1][1]) && !/_wpnonce/.test(calls[calls.length-1][1]));
  ok('srcdoc set', d.querySelector('.signa-pv__iframe').srcdoc === '<p>pv</p>');
  d.querySelector('[data-signa-add-row]').click();
  ok('repeater row added + dirty', d.querySelectorAll('[data-signa-rows] .signa-repeater__row').length === 1 && bar.dataset.state === 'dirty');
  d.getElementById('signa-settings').dispatchEvent(new w.Event('submit', { cancelable: true }));
  ok('saving', bar.dataset.state === 'saving');
  setTimeout(() => {
    ok('saved (demo): ' + bar.textContent.trim().slice(0, 30), bar.dataset.state === 'clean');
    // The real path: options.php redirects back; the sanitiser's notices come along.
    w.signaOtpAdmin.demo = false;
    const form = d.getElementById('signa-settings');
    const answer = (url, body) => { w.fetch = () => Promise.resolve({ ok: true, url, text: () => Promise.resolve(body) }); };
    answer('http://x.test/wp-admin/admin.php?page=signa&tab=channels&settings-updated=true', '<div class="notice notice-error"><p>کلید API خالی است.</p></div>');
    form.dispatchEvent(new w.Event('submit', { cancelable: true }));
    setTimeout(() => {
      ok('a sanitiser error is shown: ' + d.querySelector('[data-signa-save-state]').textContent, bar.dataset.state === 'error' && /کلید API/.test(bar.textContent));
      answer('http://x.test/wp-login.php', '<form id="loginform"></form>');
      form.dispatchEvent(new w.Event('submit', { cancelable: true }));
      setTimeout(() => {
        ok('a lost session is not reported as saved', bar.dataset.state === 'error');
        answer('http://x.test/wp-admin/admin.php?page=signa&settings-updated=true', '<div class="notice notice-success"><p>ok</p></div>');
        form.dispatchEvent(new w.Event('submit', { cancelable: true }));
        setTimeout(() => ok('a clean save is clean', bar.dataset.state === 'clean'), 30);
      }, 30);
    }, 30);
  }, 700);
}, 50);
}
