#!/usr/bin/env node
/**
 * Build the two public sites from the plugin itself:
 *
 *   web/signa/        the landing page   → parsena.ir/signa/
 *   web/signa/demo/   the live demo      → parsena.ir/signa/demo/
 *
 * One folder to upload: web/signa goes to public_html/signa. The two pages
 * link to each other with relative addresses, so they work on any domain.
 *
 * Both are plain static files (no PHP, no database), sized for a small host.
 * Nothing is drawn by hand twice:
 *
 * - the form, its stylesheet, its script and the fonts are the plugin's own
 *   files from signa/assets;
 * - the admin screens are the pages tools/admin-demo.js generates from the
 *   plugin's real PHP output (preview/public/admin*.html);
 * - the REST answers are the mock backend of preview/server.js, lifted out at
 *   build time and run inside the browser by site/shared/demo-shim.js.
 *
 * Usage:
 *   node tools/build_site.js           write web/
 *   node tools/build_site.js --check   exit 1 when web/ is not what this builds
 */
'use strict';

const fs = require('fs');
const path = require('path');

const REPO = path.join(__dirname, '..');
const SITE = path.join(REPO, 'site');
const PREVIEW = path.join(REPO, 'preview', 'public');
const ASSETS = path.join(REPO, 'signa', 'assets');
const OUT = path.join(REPO, 'web');

const read = (...parts) => fs.readFileSync(path.join(...parts), 'utf8');

/* ------------------------------------------------------------------ inputs */

const config = JSON.parse(read(SITE, 'site.json'));
const version = /Version:\s*([0-9.]+)/.exec(read(REPO, 'signa', 'signa.php'))[1];
const faDigits = (text) => String(text).replace(/[0-9]/g, (d) => '۰۱۲۳۴۵۶۷۸۹'[d]);
const versionFa = faDigits(version);

function fail(message) {
	console.error('build_site: ' + message);
	process.exit(1);
}

function between(text, start, end, label) {
	const a = text.indexOf(start);
	const b = text.indexOf(end, a + start.length);

	if (a < 0 || b < 0) {
		fail('marker not found for ' + label + ': ' + (a < 0 ? start : end));
	}

	return { before: text.slice(0, a), inner: text.slice(a + start.length, b), after: text.slice(b + end.length), start: a, end: b };
}

function replaceOnce(text, find, replacement, label) {
	const at = typeof find === 'string' ? text.indexOf(find) : text.search(find);

	if (at < 0) {
		fail('pattern not found (' + label + '): ' + find);
	}

	return text.replace(find, replacement);
}

/* The mock backend, as written in preview/server.js, wrapped for a browser. */
function mockScript() {
	const server = read(REPO, 'preview', 'server.js');
	const part = between(
		server,
		'/* ------------------------------------------------------------- mock backend */',
		'/* -------------------------------------------------------------- http server */',
		'mock backend'
	).inner;

	if (/require\(|process\.|fs\.|__dirname/.test(part)) {
		fail('the mock section of preview/server.js now uses Node APIs; it must stay browser-safe');
	}

	return [
		'/* Generated by tools/build_site.js from preview/server.js (mock backend). Do not edit. */',
		'(function () {',
		"\t'use strict';",
		// /form-config hands out the REST address and the form adopts it.
		part.trim().replace(/\/mock\/signa\/v1\//g, 'demo-api/signa/v1/'),
		'',
		'\twindow.SignaDemoMock = { handleRest: handleRest };',
		'})();',
		'',
	].join('\n');
}

/* -------------------------------------------------------------- rewriting */

function rewrite(html) {
	return html
		.replace(/\/plugin-assets\//g, 'assets/')
		.replace(/\/mock\/signa\/v1\//g, 'demo-api/signa/v1/')
		.replace(/(src|data-url)="\/admin\/form-preview"/g, (m, attr) => (attr === 'src' ? 'src="admin-preview-phone.html"' : 'data-url="form-preview"'))
		// Screen links keep their query and fragment. The generator prints the
		// reports range as `/admin/reports&amp;range=7`; the first & is a ?.
		.replace(/href="\/admin\/(settings|reports|logs|tools|access)([?&#][^"]*)?"/g, (m, screen, rest) => {
			const tail = (rest || '').replace(/^&(amp;)?/, '?');
			return 'href="admin-' + screen + '.html' + tail + '"';
		})
		.replace(/href="\/admin"/g, 'href="admin.html"')
		.replace(/href="\/account"/g, 'href="account.html"')
		.replace(/href="\/woodmart"/g, 'href="woodmart.html"')
		.replace(/href="\/"/g, 'href="index.html"');
}

function buyButton(size) {
	const cls = size === 'strip' ? 'sg-strip__btn' : 'btn' + (size === 'small' ? ' btn--sm' : '');

	if (config.buyUrl) {
		return '<a class="' + cls + '" href="' + config.buyUrl + '">خرید از راست‌چین</a>';
	}

	return '<a class="' + cls + '" aria-disabled="true">به‌زودی در راست‌چین</a>';
}

// The mark: a phone with a tick, sending out a signal.
const MARK = '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="3.5" y="3" width="11" height="18" rx="2.8"/><path d="M7.8 6h2.4"/><path d="m6.6 12.3 1.8 1.8 3.3-3.7"/><path class="w1" d="M17.2 9.3a3.8 3.8 0 0 1 0 5.4"/><path class="w2" d="M19.6 7.1a7 7 0 0 1 0 9.8"/></svg>';

const NAV = [
	['index.html', 'فرم ورود'],
	['account.html', 'حساب کاربری'],
	['woodmart.html', 'کشوی وودمارت'],
	['admin.html', 'پیشخوان مدیریت'],
];

function strip(current) {
	const links = NAV.map(([href, label]) => '<a href="' + href + '"' + (href === current ? ' aria-current="page"' : '') + '>' + label + '</a>').join('');

	return [
		'<div class="sg-strip" role="navigation" aria-label="دموی سیگنا">',
		'<div class="sg-strip__in">',
		'<a class="sg-strip__brand" href="index.html"><span class="sg-strip__mark">' + MARK + '</span><span class="sg-strip__name">سیگنا<small><i class="sg-strip__live"></i>دمو · نسخهٔ ' + versionFa + '</small></span></a>',
		'<nav class="sg-strip__nav">' + links + '</nav>',
		'<span class="sg-strip__note">پیامک واقعی فرستاده نمی‌شود</span>',
		'<span class="sg-strip__end"><a class="sg-strip__btn sg-strip__btn--ghost" href="../">معرفی سیگنا</a>' + buyButton('strip') + '</span>',
		'</div>',
		'<div class="sg-strip__signal" aria-hidden="true"><i></i></div>',
		'</div>',
	].join('\n');
}

const DEMO_HEAD = [
	'<link rel="stylesheet" href="assets/demo.css">',
	'<link rel="stylesheet" href="assets/demo-phone.css">',
	'<script src="assets/js/demo-mock.js"></script>',
	'<script src="assets/js/demo-shim.js"></script>',
	'<script src="assets/js/demo-phone.js"></script>',
].join('\n');

function chrome(html, current) {
	html = replaceOnce(html, '</head>', DEMO_HEAD + '\n</head>', 'head');
	html = html.replace(/<body([^>]*)>/, (m) => m + '\n' + strip(current));

	return html;
}

/* ------------------------------------------------------------------ pages */

/*
 * The live form as it appears on the plugin's own preview page: its markup
 * (FormRenderer output) and the signaOtp block wp_localize_script prints.
 */
function liveForm() {
	const index = read(PREVIEW, 'index.html');
	const form = between(index, '<!-- ↓↓↓ markup produced by FormRenderer::render() ↓↓↓ -->', '<!-- ↑↑↑ end of FormRenderer output ↑↑↑ -->', 'form markup').inner;
	const cfgStart = index.indexOf('<script>\n\t/* Stands in for wp_localize_script');
	const cfgEnd = index.indexOf('</script>', cfgStart);

	if (cfgStart < 0 || cfgEnd < 0) {
		fail('index.html: the signaOtp config block was not found');
	}

	/* The demo skips the sign-up step, so its progress bar has two steps. */
	const twoSteps = replaceOnce(
		replaceOnce(form, /\s*<li data-signa-step-marker="fields">[^<]*<\/li>/, '', 'fields step marker'),
		'گام ۱ از ۳',
		'گام ۱ از ۲',
		'step sentence'
	);

	return { form: twoSteps.trim(), cfg: index.slice(cfgStart, cfgEnd + '</script>'.length) };
}

/* The stage both pages share: the form in a browser frame, the appearance
   studio under it, and the phone the demo SMS arrives on. */
function stage(html, phoneAttrs) {
	const live = liveForm();
	let part = read(SITE, 'shared', 'stage.html');

	part = replaceOnce(part, '<!-- @signa-form -->', live.form, 'form slot');
	part = replaceOnce(part, '<!-- @phone-attrs -->', phoneAttrs, 'phone attributes');
	html = replaceOnce(html, '<!-- @stage -->', part.replace(/\s+$/, ''), 'stage slot');
	html = replaceOnce(html, '<!-- @signa-config -->', live.cfg, 'config slot');

	return html;
}

function fillIn(html, where, fill) {
	for (const [key, value] of Object.entries(fill)) {
		if (html.indexOf(key) < 0) {
			fail(where + ': placeholder ' + key + ' is not used');
		}
		html = html.split(key).join(value);
	}

	return html;
}

const SITE_SCRIPTS = '<script src="assets/js/demo-studio.js"></script>\n<script src="assets/js/site.js"></script>';

function demoIndex() {
	let html = read(SITE, 'demo', 'index.html');

	html = fillIn(html, 'demo index', { '{{version_fa}}': versionFa });
	// After signing in, the phone offers the member page.
	html = stage(html, ' data-sg-next="account.html"');
	html = replaceOnce(html, '</head>', SITE_SCRIPTS + '\n</head>', 'demo index scripts');

	return chrome(rewrite(html), 'index.html');
}

function demoAccount() {
	let html = read(PREVIEW, 'account.html');

	html = replaceOnce(html, /<div class="demo-bar">[\s\S]*?<\/nav>\s*<\/div>\n/, '', 'account bar');
	html = html.replace(/\s*\(نسخهٔ [۰-۹.]+\)/g, '');

	return chrome(rewrite(html), 'account.html');
}

function demoWoodmart() {
	let html = read(PREVIEW, 'woodmart.html');

	html = replaceOnce(html, /<nav class="wm-bar">[\s\S]*?<\/nav>\n/, '', 'woodmart bar');

	return chrome(rewrite(html), 'woodmart.html');
}

function demoAdmin(file) {
	let html = read(PREVIEW, file);

	html = replaceOnce(html, /<div class="demo-bar">[\s\S]*?<\/div>\n/, '', file + ' bar');
	html = html.replace('(پیش‌نمایش)', '(دمو)');

	return chrome(rewrite(html), 'admin.html');
}

function landing() {
	let html = read(SITE, 'landing', 'index.html');

	html = fillIn(html, 'landing', {
		'{{version_fa}}': versionFa,
		'{{demo_url}}': 'demo/',
		'{{buy_small}}': buyButton('small'),
		'{{buy_large}}': buyButton('large'),
	});

	html = replaceOnce(html, '<!-- @brand-mark -->', '<span class="brand__mark">' + MARK + '</span>', 'brand mark');
	html = replaceOnce(html, '<!-- @brand-mark-plain -->', MARK, 'plugin row mark');
	html = stage(html, '');
	html = replaceOnce(html, '<!-- @demo-head -->', [
		'<link rel="stylesheet" href="assets/demo-phone.css">',
		'<script src="assets/js/demo-mock.js"></script>',
		'<script src="assets/js/demo-shim.js"></script>',
		'<script src="assets/js/demo-phone.js"></script>',
		SITE_SCRIPTS,
	].join('\n'), 'head slot');

	return rewrite(html);
}

const HTACCESS = [
	'# Static site: no PHP runs here.',
	'Options -Indexes',
	'AddDefaultCharset utf-8',
	'AddType font/woff2 .woff2',
	'<IfModule mod_deflate.c>',
	'  AddOutputFilterByType DEFLATE text/html text/css application/javascript image/svg+xml',
	'</IfModule>',
	'<IfModule mod_expires.c>',
	'  ExpiresActive On',
	'  ExpiresByType text/css "access plus 7 days"',
	'  ExpiresByType application/javascript "access plus 7 days"',
	'  ExpiresByType font/woff2 "access plus 1 year"',
	'  ExpiresByType text/html "access plus 0 seconds"',
	'</IfModule>',
	'',
].join('\n');

/* ------------------------------------------------------------ comments out */

let acorn = null;

function jsComments(text) {
	if (!acorn) {
		try {
			acorn = require('acorn');
		} catch (error) {
			fail('acorn is needed to build the site: npm install --no-save acorn');
		}
	}

	const ranges = [];
	acorn.parse(text, { ecmaVersion: 'latest', sourceType: 'script', onComment: (block, body, start, end) => ranges.push([start, end]) });
	return ranges;
}

function cssComments(text) {
	const ranges = [];
	let quote = null;

	for (let i = 0; i < text.length; i++) {
		const c = text[i];
		if (quote) {
			if (c === '\\') {
				i++;
			} else if (c === quote) {
				quote = null;
			}
		} else if (c === '"' || c === "'") {
			quote = c;
		} else if (c === '/' && text[i + 1] === '*') {
			const end = text.indexOf('*/', i + 2);
			ranges.push([i, end + 2]);
			i = end + 1;
		}
	}

	return ranges;
}

function cut(text, ranges) {
	if (!ranges.length) {
		return text;
	}

	let out = '';
	let at = 0;
	for (const [a, b] of ranges) {
		out += text.slice(at, a) + '\u0000';
		at = b;
	}
	out += text.slice(at);

	return out
		.split('\n')
		.filter((line) => !(line.includes('\u0000') && line.replace(/\u0000/g, '').trim() === ''))
		.map((line) => (line.includes('\u0000') ? line.replace(/\u0000/g, '').replace(/[ \t]+$/, '') : line))
		.join('\n')
		.replace(/\n{3,}/g, '\n\n');
}

function htmlComments(text) {
	const parts = text.split(/(<script\b[^>]*>[\s\S]*?<\/script>|<style\b[^>]*>[\s\S]*?<\/style>)/);

	return parts
		.map((part, i) => {
			if (i % 2 === 0) {
				const ranges = [];
				part.replace(/<!--[\s\S]*?-->/g, (m, at) => ranges.push([at, at + m.length]));
				return cut(part, ranges);
			}
			const m = /^(<(script|style)\b[^>]*>)([\s\S]*?)(<\/\2>)$/.exec(part);
			if (m[2] === 'style') {
				return m[1] + cut(m[3], cssComments(m[3])) + m[4];
			}
			if (/\bsrc=|type="application\/(ld\+)?json"/.test(m[1]) || !m[3].trim()) {
				return part;
			}
			return m[1] + cut(m[3], jsComments(m[3])) + m[4];
		})
		.join('');
}

function withoutComments(name, data) {
	if (/\.js$/.test(name)) {
		return cut(data, jsComments(data));
	}
	if (/\.css$/.test(name)) {
		return cut(data, cssComments(data));
	}
	if (/\.html$/.test(name)) {
		return htmlComments(data);
	}
	if (/\.htaccess$/.test(name)) {
		return data.replace(/^#.*\n/gm, '');
	}
	return data;
}

/* ------------------------------------------------------------------ output */

function files() {
	const out = new Map();
	const put = (name, data) => {
		const text = /\.(html|js|css|htaccess)$/.test(name) ? withoutComments(name, data.toString('utf8')) : data;
		out.set(name, Buffer.isBuffer(text) ? text : Buffer.from(text, 'utf8'));
	};
	const copy = (name, ...src) => put(name, fs.readFileSync(path.join(...src)));

	const mock = mockScript();
	const shared = (root, admin) => {
		copy(root + '/assets/css/front.css', ASSETS, 'css', 'front.css');
		copy(root + '/assets/js/front.js', ASSETS, 'js', 'front.js');
		for (const font of fs.readdirSync(path.join(ASSETS, 'fonts')).sort()) {
			if (/\.(woff2|txt)$/.test(font)) {
				copy(root + '/assets/fonts/' + font, ASSETS, 'fonts', font);
			}
		}
		if (admin) {
			copy(root + '/assets/css/admin.css', ASSETS, 'css', 'admin.css');
			copy(root + '/assets/js/admin.js', ASSETS, 'js', 'admin.js');
		}
		put(root + '/assets/js/demo-mock.js', mock);
		copy(root + '/assets/js/demo-shim.js', SITE, 'shared', 'demo-shim.js');
		copy(root + '/assets/js/demo-phone.js', SITE, 'shared', 'demo-phone.js');
		copy(root + '/assets/demo-phone.css', SITE, 'shared', 'demo-phone.css');
		copy(root + '/assets/js/demo-studio.js', SITE, 'shared', 'demo-studio.js');
		copy(root + '/assets/js/site.js', SITE, 'shared', 'site.js');
		copy(root + '/assets/landing.css', SITE, 'landing', 'landing.css');
		put(root + '/.htaccess', HTACCESS);
	};

	shared('signa', false);
	put('signa/index.html', landing());

	shared('signa/demo', true);
	copy('signa/demo/assets/demo.css', SITE, 'shared', 'demo.css');
	put('signa/demo/index.html', demoIndex());
	put('signa/demo/account.html', demoAccount());
	put('signa/demo/woodmart.html', demoWoodmart());

	for (const file of fs.readdirSync(PREVIEW).sort()) {
		if (/^admin(-[a-z]+)?\.html$/.test(file) && !/^admin-preview-/.test(file)) {
			put('signa/demo/' + file, demoAdmin(file));
		} else if (/^admin-preview-[a-z]+\.html$/.test(file)) {
			put('signa/demo/' + file, rewrite(read(PREVIEW, file)));
		}
	}

	return out;
}

/* What must never reach a public page. */
function audit(out) {
	const problems = [];

	for (const [name, data] of out) {
		if (!/\.(html|js|css)$/.test(name)) {
			continue;
		}

		const text = data.toString('utf8');

		if (/\.html$/.test(name)) {
			const rooted = text.match(/(?:href|src|action|data-url)="\/(?!\/)[^"]*"/g);
			if (rooted) {
				problems.push(name + ': root-relative address ' + rooted[0] + ' (breaks under a sub-folder)');
			}
			if (/download\/signa\.zip|signa\.zip"/.test(text)) {
				problems.push(name + ': links to the plugin package');
			}
			if (/\/mock\//.test(text)) {
				problems.push(name + ': still points at the preview server mock');
			}
		}

		if (/\/mock\/signa\//.test(text)) {
			problems.push(name + ': still points at the preview server mock');
		}

		if (/t\.me\/|instagram\.com|wa\.me\/|mailto:|@gmail\.|github\.com\/(?!rastikerdar)/i.test(text)) {
			problems.push(name + ': personal link or contact');
		}

		// Written as a character class so the brand check does not match this file.
		if (/t[i]sa|ت[ی]سا/i.test(text)) {
			problems.push(name + ': old client name');
		}
	}

	if (problems.length) {
		fail('refusing to write the site:\n  ' + problems.join('\n  '));
	}
}

function walk(dir, base = dir, list = []) {
	if (!fs.existsSync(dir)) {
		return list;
	}

	for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
		const full = path.join(dir, entry.name);
		if (entry.isDirectory()) {
			walk(full, base, list);
		} else {
			list.push(path.relative(base, full).split(path.sep).join('/'));
		}
	}

	return list;
}

function main() {
	const out = files();
	audit(out);

	if (process.argv.includes('--check')) {
		const onDisk = new Set(walk(OUT));
		const drift = [];

		for (const [name, data] of out) {
			const target = path.join(OUT, name);
			if (!fs.existsSync(target) || !fs.readFileSync(target).equals(data)) {
				drift.push(name);
			}
			onDisk.delete(name);
		}

		drift.push(...[...onDisk].map((name) => name + ' (stale)'));

		if (drift.length) {
			fail('web/ is out of date; run node tools/build_site.js\n  ' + drift.slice(0, 20).join('\n  '));
		}

		console.log('site check ok: ' + out.size + ' files');
		return;
	}

	fs.rmSync(OUT, { recursive: true, force: true });

	let bytes = { signa: 0, demo: 0 };
	for (const [name, data] of out) {
		const target = path.join(OUT, name);
		fs.mkdirSync(path.dirname(target), { recursive: true });
		fs.writeFileSync(target, data);
		bytes[name.startsWith('signa/demo/') ? 'demo' : 'signa'] += data.length;
	}

	const kb = (n) => Math.round(n / 1024) + ' KB';
	console.log('wrote web/signa (' + kb(bytes.signa) + ') with the demo in web/signa/demo (' + kb(bytes.demo) + '), ' + out.size + ' files, version ' + version);
}

main();
