#!/usr/bin/env node
/**
 * Build the two public sites from the plugin itself:
 *
 *   web/signa/   the landing page     → upload to parsena.ir/signa/
 *   web/demo/    the live demo        → upload to the root of demo.parsena.ir
 *
 * Both are plain static files (no PHP, no database), sized for a small host.
 * Nothing is drawn by hand twice:
 *
 * - the form, its stylesheet, its script and the fonts are the plugin's own
 *   files from signa/assets;
 * - the admin screens are the pages tools/admin-demo.js generates from the
 *   plugin's real PHP output (preview/public/admin*.html);
 * - the REST answers are the mock backend of preview/server.js, lifted out at
 *   build time and run inside the browser by site/shared/demo-shim.js.
 *
 * Usage:
 *   node tools/build_site.js           write web/
 *   node tools/build_site.js --check   exit 1 when web/ is not what this builds
 */
'use strict';

const fs = require('fs');
const path = require('path');

const REPO = path.join(__dirname, '..');
const SITE = path.join(REPO, 'site');
const PREVIEW = path.join(REPO, 'preview', 'public');
const ASSETS = path.join(REPO, 'signa', 'assets');
const OUT = path.join(REPO, 'web');

const read = (...parts) => fs.readFileSync(path.join(...parts), 'utf8');

/* ------------------------------------------------------------------ inputs */

const config = JSON.parse(read(SITE, 'site.json'));
const version = /Version:\s*([0-9.]+)/.exec(read(REPO, 'signa', 'signa.php'))[1];
const faDigits = (text) => String(text).replace(/[0-9]/g, (d) => '۰۱۲۳۴۵۶۷۸۹'[d]);
const versionFa = faDigits(version);

function fail(message) {
	console.error('build_site: ' + message);
	process.exit(1);
}

function between(text, start, end, label) {
	const a = text.indexOf(start);
	const b = text.indexOf(end, a + start.length);

	if (a < 0 || b < 0) {
		fail('marker not found for ' + label + ': ' + (a < 0 ? start : end));
	}

	return { before: text.slice(0, a), inner: text.slice(a + start.length, b), after: text.slice(b + end.length), start: a, end: b };
}

function replaceOnce(text, find, replacement, label) {
	const at = typeof find === 'string' ? text.indexOf(find) : text.search(find);

	if (at < 0) {
		fail('pattern not found (' + label + '): ' + find);
	}

	return text.replace(find, replacement);
}

/* The mock backend, as written in preview/server.js, wrapped for a browser. */
function mockScript() {
	const server = read(REPO, 'preview', 'server.js');
	const part = between(
		server,
		'/* ------------------------------------------------------------- mock backend */',
		'/* -------------------------------------------------------------- http server */',
		'mock backend'
	).inner;

	if (/require\(|process\.|fs\.|__dirname/.test(part)) {
		fail('the mock section of preview/server.js now uses Node APIs; it must stay browser-safe');
	}

	return [
		'/* Generated by tools/build_site.js from preview/server.js (mock backend). Do not edit. */',
		'(function () {',
		"\t'use strict';",
		// /form-config hands out the REST address and the form adopts it.
		part.trim().replace(/\/mock\/signa\/v1\//g, 'demo-api/signa/v1/'),
		'',
		'\twindow.SignaDemoMock = { handleRest: handleRest };',
		'})();',
		'',
	].join('\n');
}

/* -------------------------------------------------------------- rewriting */

function rewrite(html) {
	return html
		.replace(/\/plugin-assets\//g, 'assets/')
		.replace(/\/mock\/signa\/v1\//g, 'demo-api/signa/v1/')
		.replace(/(src|data-url)="\/admin\/form-preview"/g, (m, attr) => (attr === 'src' ? 'src="admin-preview-phone.html"' : 'data-url="form-preview"'))
		// Screen links keep their query and fragment. The generator prints the
		// reports range as `/admin/reports&amp;range=7`; the first & is a ?.
		.replace(/href="\/admin\/(settings|reports|logs|tools|access)([?&#][^"]*)?"/g, (m, screen, rest) => {
			const tail = (rest || '').replace(/^&(amp;)?/, '?');
			return 'href="admin-' + screen + '.html' + tail + '"';
		})
		.replace(/href="\/admin"/g, 'href="admin.html"')
		.replace(/href="\/account"/g, 'href="account.html"')
		.replace(/href="\/woodmart"/g, 'href="woodmart.html"')
		.replace(/href="\/"/g, 'href="index.html"');
}

function buyButton(size) {
	const cls = size === 'strip' ? 'sg-strip__btn' : 'btn' + (size === 'small' ? ' btn--sm' : '');

	if (config.buyUrl) {
		return '<a class="' + cls + '" href="' + config.buyUrl + '">خرید از راست‌چین</a>';
	}

	return '<a class="' + cls + '" aria-disabled="true">به‌زودی در راست‌چین</a>';
}

const MARK = '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="6" y="2.5" width="12" height="19" rx="3"/><path d="M10.5 5.5h3"/><path d="M9 12.5l2 2 4-4.5"/></svg>';

const NAV = [
	['index.html', 'فرم ورود'],
	['account.html', 'حساب کاربری'],
	['woodmart.html', 'کشوی وودمارت'],
	['admin.html', 'پیشخوان مدیریت'],
];

function strip(current) {
	const links = NAV.map(([href, label]) => '<a href="' + href + '"' + (href === current ? ' aria-current="page"' : '') + '>' + label + '</a>').join('');

	return [
		'<div class="sg-strip" role="navigation" aria-label="دموی سیگنا">',
		'<a class="sg-strip__brand" href="index.html"><span class="sg-strip__mark">' + MARK + '</span><span>سیگنا<small>دموی زنده · نسخهٔ ' + versionFa + '</small></span></a>',
		'<nav class="sg-strip__nav">' + links + '</nav>',
		'<span class="sg-strip__note">داده‌ها نمونه‌اند و پیامکی ارسال نمی‌شود · کد آزمایشی <b>12345</b></span>',
		'<span class="sg-strip__end"><a class="sg-strip__btn sg-strip__btn--ghost" href="' + config.landingUrl + '">معرفی سیگنا</a>' + buyButton('strip') + '</span>',
		'</div>',
	].join('\n');
}

const DEMO_HEAD = [
	'<link rel="stylesheet" href="assets/demo.css">',
	'<script src="assets/js/demo-mock.js"></script>',
	'<script src="assets/js/demo-shim.js"></script>',
].join('\n');

function chrome(html, current) {
	html = replaceOnce(html, '</head>', DEMO_HEAD + '\n</head>', 'head');
	html = html.replace(/<body([^>]*)>/, (m) => m + '\n' + strip(current));

	return html;
}

/* ------------------------------------------------------------------ pages */

function demoIndex() {
	let html = read(PREVIEW, 'index.html');

	// The developer bar (with its download link) gives way to the demo strip.
	const bar = html.indexOf('<div class="demo-bar">');
	const stage = html.indexOf('<div class="demo-stage">');

	if (bar < 0 || stage < bar) {
		fail('index.html: demo bar not found');
	}

	html = html.slice(0, bar) + html.slice(stage);
	html = replaceOnce(html, /<title>[^<]*<\/title>/, '<title>دموی زندهٔ سیگنا — فرم ورود و عضویت</title>', 'index title');

	// The sticky controls sat under the old bar; the strip is a little shorter.
	html = html.replace('top: 78px;', 'top: 74px;');

	// Keep the behaviour a buyer can judge; the cache and timeout drills are
	// for development and need the preview server.
	for (const name of ['stale-nonce', 'stale-form', 'captcha', 'short-timeout', 'webotp']) {
		html = replaceOnce(html, new RegExp('\\s*<button[^>]*data-behavior="' + name + '"[^>]*>[^<]*</button>'), '', 'behaviour ' + name);
	}

	html = replaceOnce(html, /\s*<p class="demo-hints">\s*«nonce کهنه»[\s\S]*?<\/p>/, '', 'behaviour hint');
	html = replaceOnce(html, /\s*<span><code>09111111111<\/code>[^<]*<\/span>/, '', 'captcha number');

	// Only the captcha drill (removed above) used this address.
	html = html.replace("'/mock/captcha-unreachable.js'", "'captcha-unreachable.js'");

	// After a successful sign-in, show what the member sees.
	html = replaceOnce(html, 'data-redirect=""', 'data-redirect="account.html"', 'redirect');

	return chrome(rewrite(html), 'index.html');
}

function demoAccount() {
	let html = read(PREVIEW, 'account.html');

	html = replaceOnce(html, /<div class="demo-bar">[\s\S]*?<\/nav>\s*<\/div>\n/, '', 'account bar');
	html = html.replace(/\s*\(نسخهٔ [۰-۹.]+\)/g, '');

	return chrome(rewrite(html), 'account.html');
}

function demoWoodmart() {
	let html = read(PREVIEW, 'woodmart.html');

	html = replaceOnce(html, /<nav class="wm-bar">[\s\S]*?<\/nav>\n/, '', 'woodmart bar');

	return chrome(rewrite(html), 'woodmart.html');
}

function demoAdmin(file) {
	let html = read(PREVIEW, file);

	html = replaceOnce(html, /<div class="demo-bar">[\s\S]*?<\/div>\n/, '', file + ' bar');
	html = html.replace('(پیش‌نمایش)', '(دمو)');

	return chrome(rewrite(html), 'admin.html');
}

function landing() {
	let html = read(SITE, 'landing', 'index.html');
	const index = read(PREVIEW, 'index.html');

	const form = between(index, '<!-- ↓↓↓ markup produced by FormRenderer::render() ↓↓↓ -->', '<!-- ↑↑↑ end of FormRenderer output ↑↑↑ -->', 'form markup').inner;
	const cfgStart = index.indexOf('<script>\n\t/* Stands in for wp_localize_script');
	const cfgEnd = index.indexOf('</script>', cfgStart);

	if (cfgStart < 0 || cfgEnd < 0) {
		fail('index.html: the signaOtp config block was not found');
	}

	const cfg = index.slice(cfgStart, cfgEnd + '</script>'.length);

	const fill = {
		'{{version_fa}}': versionFa,
		'{{demo_url}}': config.demoUrl,
		'{{buy_small}}': buyButton('small'),
		'{{buy_large}}': buyButton('large'),
	};

	for (const [key, value] of Object.entries(fill)) {
		if (html.indexOf(key) < 0) {
			fail('landing: placeholder ' + key + ' is not used');
		}
		html = html.split(key).join(value);
	}

	html = replaceOnce(html, '<!-- @signa-form -->', form.trim(), 'form slot');
	html = replaceOnce(html, '<!-- @signa-config -->', cfg, 'config slot');
	html = replaceOnce(html, '<!-- @demo-head -->', '<script src="assets/js/demo-mock.js"></script>\n<script src="assets/js/demo-shim.js"></script>', 'head slot');

	return rewrite(html);
}

const HTACCESS = [
	'# Static site: no PHP runs here.',
	'Options -Indexes',
	'AddDefaultCharset utf-8',
	'AddType font/woff2 .woff2',
	'<IfModule mod_deflate.c>',
	'  AddOutputFilterByType DEFLATE text/html text/css application/javascript image/svg+xml',
	'</IfModule>',
	'<IfModule mod_expires.c>',
	'  ExpiresActive On',
	'  ExpiresByType text/css "access plus 7 days"',
	'  ExpiresByType application/javascript "access plus 7 days"',
	'  ExpiresByType font/woff2 "access plus 1 year"',
	'  ExpiresByType text/html "access plus 0 seconds"',
	'</IfModule>',
	'',
].join('\n');

/* ------------------------------------------------------------------ output */

function files() {
	const out = new Map();
	const put = (name, data) => out.set(name, Buffer.isBuffer(data) ? data : Buffer.from(data, 'utf8'));
	const copy = (name, ...src) => put(name, fs.readFileSync(path.join(...src)));

	const mock = mockScript();
	const shared = (root, admin) => {
		copy(root + '/assets/css/front.css', ASSETS, 'css', 'front.css');
		copy(root + '/assets/js/front.js', ASSETS, 'js', 'front.js');
		for (const font of fs.readdirSync(path.join(ASSETS, 'fonts')).sort()) {
			if (/\.(woff2|txt)$/.test(font)) {
				copy(root + '/assets/fonts/' + font, ASSETS, 'fonts', font);
			}
		}
		if (admin) {
			copy(root + '/assets/css/admin.css', ASSETS, 'css', 'admin.css');
			copy(root + '/assets/js/admin.js', ASSETS, 'js', 'admin.js');
		}
		put(root + '/assets/js/demo-mock.js', mock);
		copy(root + '/assets/js/demo-shim.js', SITE, 'shared', 'demo-shim.js');
		put(root + '/.htaccess', HTACCESS);
	};

	shared('signa', false);
	copy('signa/assets/landing.css', SITE, 'landing', 'landing.css');
	put('signa/index.html', landing());

	shared('demo', true);
	copy('demo/assets/demo.css', SITE, 'shared', 'demo.css');
	put('demo/index.html', demoIndex());
	put('demo/account.html', demoAccount());
	put('demo/woodmart.html', demoWoodmart());

	for (const file of fs.readdirSync(PREVIEW).sort()) {
		if (/^admin(-[a-z]+)?\.html$/.test(file) && !/^admin-preview-/.test(file)) {
			put('demo/' + file, demoAdmin(file));
		} else if (/^admin-preview-[a-z]+\.html$/.test(file)) {
			put('demo/' + file, rewrite(read(PREVIEW, file)));
		}
	}

	return out;
}

/* What must never reach a public page. */
function audit(out) {
	const problems = [];

	for (const [name, data] of out) {
		if (!/\.(html|js|css)$/.test(name)) {
			continue;
		}

		const text = data.toString('utf8');

		if (/\.html$/.test(name)) {
			const rooted = text.match(/(?:href|src|action|data-url)="\/(?!\/)[^"]*"/g);
			if (rooted) {
				problems.push(name + ': root-relative address ' + rooted[0] + ' (breaks under a sub-folder)');
			}
			if (/download\/signa\.zip|signa\.zip"/.test(text)) {
				problems.push(name + ': links to the plugin package');
			}
			if (/\/mock\//.test(text)) {
				problems.push(name + ': still points at the preview server mock');
			}
		}

		if (/\/mock\/signa\//.test(text)) {
			problems.push(name + ': still points at the preview server mock');
		}

		if (/t\.me\/|instagram\.com|wa\.me\/|mailto:|@gmail\.|github\.com\/(?!rastikerdar)/i.test(text)) {
			problems.push(name + ': personal link or contact');
		}

		// Written as a character class so the brand check does not match this file.
		if (/t[i]sa|ت[ی]سا/i.test(text)) {
			problems.push(name + ': old client name');
		}
	}

	if (problems.length) {
		fail('refusing to write the site:\n  ' + problems.join('\n  '));
	}
}

function walk(dir, base = dir, list = []) {
	if (!fs.existsSync(dir)) {
		return list;
	}

	for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
		const full = path.join(dir, entry.name);
		if (entry.isDirectory()) {
			walk(full, base, list);
		} else {
			list.push(path.relative(base, full).split(path.sep).join('/'));
		}
	}

	return list;
}

function main() {
	const out = files();
	audit(out);

	if (process.argv.includes('--check')) {
		const onDisk = new Set(walk(OUT));
		const drift = [];

		for (const [name, data] of out) {
			const target = path.join(OUT, name);
			if (!fs.existsSync(target) || !fs.readFileSync(target).equals(data)) {
				drift.push(name);
			}
			onDisk.delete(name);
		}

		drift.push(...[...onDisk].map((name) => name + ' (stale)'));

		if (drift.length) {
			fail('web/ is out of date; run node tools/build_site.js\n  ' + drift.slice(0, 20).join('\n  '));
		}

		console.log('site check ok: ' + out.size + ' files');
		return;
	}

	fs.rmSync(OUT, { recursive: true, force: true });

	let bytes = { signa: 0, demo: 0 };
	for (const [name, data] of out) {
		const target = path.join(OUT, name);
		fs.mkdirSync(path.dirname(target), { recursive: true });
		fs.writeFileSync(target, data);
		bytes[name.split('/')[0]] += data.length;
	}

	const kb = (n) => Math.round(n / 1024) + ' KB';
	console.log('wrote web/signa (' + kb(bytes.signa) + ') and web/demo (' + kb(bytes.demo) + '), ' + out.size + ' files, version ' + version);
}

main();
